### PR TITLE
Add anchovy + leopard shark prefabs

### PR DESCRIPTION
**Pull request by jmcduff**
Small PR for adding the anchovy and leopard shark prefabs \OwO/

### CODE REVIEW

**Review by danielwiktorczyk — APPROVED** [review]
Might be better to include a subfolder for these things (e.g. Fishes)

Otherwise, file wise, looks good!

**Comment by jmcduff** [comment]
> Might be better to include a subfolder for these things (e.g. Fishes)
> 
> Otherwise, file wise, looks good!

Good point, I'll add that folder in my future PR for the leopard shark 👍

**Comment by eli-lam** [comment]
Might be out of your scope but is there any chance you can go over the mesh and flesh out some small details? Like these?
image
image

**Comment by jmcduff** [comment]
> Might be out of your scope but is there any chance you can go over the mesh and flesh out some small details? Like these?

hahaha Monster Mash is pretty clumsy to use. I can try to fix the gaps, but the waviness and pointy bits will be hard to fix.

**Comment by jmcduff** [comment]
I've fixed the anchovy model and added the leopard shark while I was at it

**Comment by jmcduff** [comment]
> Might be better to include a subfolder for these things (e.g. Fishes)

I've added a Fish subfolder

**Review by eli-lam — APPROVED** [review]

**Pull request merged**
