### PR TITLE
Add bubble particles to swimming and eating

### PR DESCRIPTION
**Pull request by Akisukei**

### CODE REVIEW

**Review by shifatkhan — CHANGES_REQUESTED** [review]
Looks very nice!
Can you speed up the bubbles when we sprint?

**Comment by Akisukei** [comment]
> Looks very nice!
> Can you speed up the bubbles when we sprint?

done

**Review by shifatkhan — CHANGES_REQUESTED** [review]
Can you also make them simulate in world position
image

**Review by shifatkhan — APPROVED** [review]
LGTM!

**Review by danielwiktorczyk — APPROVED** [review]

**Pull request merged**
